pipeline:
  test:
    image: microsoft/dotnet:2.2.103-sdk-alpine3.8
    commands:
      - "dotnet test"

  build:
    image: microsoft/dotnet:2.2.103-sdk-alpine3.8
    environment:
      CGO_ENABLED: "0"
      VERSION: "${DRONE_TAG}"
      COMMIT: "${DRONE_COMMIT_SHA:0:7}"
    commands:
      - "docker build -t drone-api ."
  publish:
    image: plugins/docker
    repo: jmccracken/drone-api