kind: pipeline
name: default

steps:
- name: test
  image: microsoft/dotnet:2.2.103-sdk-alpine3.8
  commands:
    - "dotnet test"

- name: containerize  
  image: plugins/docker
  settings:
    username: 
        from_secret: username
    password: 
        from_secret: password
    repo: jmccracken/drone-api
    auto_tag: true
    
deploy:
    image: jmccracken/drone-api
    tag: latest
    kubernetes_server: 
        from_secret: kube_server
    kubernetes_token: 
        from_secret: kube_token
    namespace: default
    deployment: drone-api
    repo: jmccracken/drone-api
    container: drone-api