kind: pipeline
name: default

steps:
- name: test
  image: microsoft/dotnet:2.2.103-sdk-alpine3.8
  commands:
    - "dotnet test"

- name: docker  
  image: plugins/docker
  settings:
    username: 
        from_secret: username
    password: 
        from_secret: password
    repo: jmccracken/drone-api
    auto_tag: true
  
- name: publish
  image: plugins/docker
  repo: jmccracken/drone-api
