kind: pipeline
name: default

steps:
- name: test
  image: microsoft/dotnet:2.2.103-sdk-alpine3.8
  commands:
    - "dotnet test"

# plugin docs - http://plugins.drone.io/drone-plugins/drone-docker/
- name: containerize  
  image: plugins/docker
  settings:
    username: 
        from_secret: username
    password: 
        from_secret: password
    repo: jmccracken/drone-api
    tags: dev

# plugin docs -  http://plugins.drone.io/mactynow/drone-kubernetes/   
- name: deploy-to-dev
  image: quay.io/honestbee/drone-kubernetes
  tag: dev
  kubernetes_server: 
    from_secret: kube_server
  kubernetes_token: 
    from_secret: kube_token
  namespace: development
  deployment: drone-api
  repo: jmccracken/drone-api
  container: drone-api
