---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drone-api
  namespace: development
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: drone-api
  template:
    metadata:
      labels:
        app: drone-api
    spec:
      containers:
      - name: drone-api
        image: jmccracken/drone-api:latest
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        ports:
        - name: http-api
          containerPort: 80
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: drone-api
  namespace: development
spec:
  type: LoadBalancer
  selector:
    app: drone-api
  ports:
  - port: 80
    name: http-balancer
    targetPort: http-api